/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as Import } from './routes/_'
import { Route as authLoginImport } from './routes/_.(auth)/login'
import { Route as appRecipesNewImport } from './routes/_.(app)/recipes/new'

// Create Virtual Routes

const appIndexLazyImport = createFileRoute('/_/(app)/')()
const appRecipesAuthorIndexLazyImport = createFileRoute(
  '/_/(app)/recipes/$author/',
)()
const appRecipesAuthorRkeyIndexLazyImport = createFileRoute(
  '/_/(app)/recipes/$author/$rkey/',
)()

// Create/Update Routes

const Route = Import.update({
  id: '/_',
  getParentRoute: () => rootRoute,
} as any)

const appIndexLazyRoute = appIndexLazyImport
  .update({
    id: '/(app)/',
    path: '/',
    getParentRoute: () => Route,
  } as any)
  .lazy(() => import('./routes/_.(app)/index.lazy').then((d) => d.Route))

const authLoginRoute = authLoginImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => Route,
} as any)

const appRecipesNewRoute = appRecipesNewImport.update({
  id: '/(app)/recipes/new',
  path: '/recipes/new',
  getParentRoute: () => Route,
} as any)

const appRecipesAuthorIndexLazyRoute = appRecipesAuthorIndexLazyImport
  .update({
    id: '/(app)/recipes/$author/',
    path: '/recipes/$author/',
    getParentRoute: () => Route,
  } as any)
  .lazy(() =>
    import('./routes/_.(app)/recipes/$author/index.lazy').then((d) => d.Route),
  )

const appRecipesAuthorRkeyIndexLazyRoute = appRecipesAuthorRkeyIndexLazyImport
  .update({
    id: '/(app)/recipes/$author/$rkey/',
    path: '/recipes/$author/$rkey/',
    getParentRoute: () => Route,
  } as any)
  .lazy(() =>
    import('./routes/_.(app)/recipes/$author/$rkey/index.lazy').then(
      (d) => d.Route,
    ),
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_': {
      id: '/_'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof Import
      parentRoute: typeof rootRoute
    }
    '/_/(auth)/login': {
      id: '/_/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginImport
      parentRoute: typeof rootRoute
    }
    '/_/(app)/': {
      id: '/_/(app)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/_/(app)/recipes/new': {
      id: '/_/(app)/recipes/new'
      path: '/recipes/new'
      fullPath: '/recipes/new'
      preLoaderRoute: typeof appRecipesNewImport
      parentRoute: typeof rootRoute
    }
    '/_/(app)/recipes/$author/': {
      id: '/_/(app)/recipes/$author/'
      path: '/recipes/$author'
      fullPath: '/recipes/$author'
      preLoaderRoute: typeof appRecipesAuthorIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/_/(app)/recipes/$author/$rkey/': {
      id: '/_/(app)/recipes/$author/$rkey/'
      path: '/recipes/$author/$rkey'
      fullPath: '/recipes/$author/$rkey'
      preLoaderRoute: typeof appRecipesAuthorRkeyIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

interface RouteChildren {
  authLoginRoute: typeof authLoginRoute
  appIndexLazyRoute: typeof appIndexLazyRoute
  appRecipesNewRoute: typeof appRecipesNewRoute
  appRecipesAuthorIndexLazyRoute: typeof appRecipesAuthorIndexLazyRoute
  appRecipesAuthorRkeyIndexLazyRoute: typeof appRecipesAuthorRkeyIndexLazyRoute
}

const RouteChildren: RouteChildren = {
  authLoginRoute: authLoginRoute,
  appIndexLazyRoute: appIndexLazyRoute,
  appRecipesNewRoute: appRecipesNewRoute,
  appRecipesAuthorIndexLazyRoute: appRecipesAuthorIndexLazyRoute,
  appRecipesAuthorRkeyIndexLazyRoute: appRecipesAuthorRkeyIndexLazyRoute,
}

const RouteWithChildren = Route._addFileChildren(RouteChildren)

export interface FileRoutesByFullPath {
  '': typeof RouteWithChildren
  '/login': typeof authLoginRoute
  '/': typeof appIndexLazyRoute
  '/recipes/new': typeof appRecipesNewRoute
  '/recipes/$author': typeof appRecipesAuthorIndexLazyRoute
  '/recipes/$author/$rkey': typeof appRecipesAuthorRkeyIndexLazyRoute
}

export interface FileRoutesByTo {
  '/login': typeof authLoginRoute
  '/': typeof appIndexLazyRoute
  '/recipes/new': typeof appRecipesNewRoute
  '/recipes/$author': typeof appRecipesAuthorIndexLazyRoute
  '/recipes/$author/$rkey': typeof appRecipesAuthorRkeyIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_': typeof RouteWithChildren
  '/_/(auth)/login': typeof authLoginRoute
  '/_/(app)/': typeof appIndexLazyRoute
  '/_/(app)/recipes/new': typeof appRecipesNewRoute
  '/_/(app)/recipes/$author/': typeof appRecipesAuthorIndexLazyRoute
  '/_/(app)/recipes/$author/$rkey/': typeof appRecipesAuthorRkeyIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/login'
    | '/'
    | '/recipes/new'
    | '/recipes/$author'
    | '/recipes/$author/$rkey'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/recipes/new'
    | '/recipes/$author'
    | '/recipes/$author/$rkey'
  id:
    | '__root__'
    | '/_'
    | '/_/(auth)/login'
    | '/_/(app)/'
    | '/_/(app)/recipes/new'
    | '/_/(app)/recipes/$author/'
    | '/_/(app)/recipes/$author/$rkey/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  Route: typeof RouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  Route: RouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_"
      ]
    },
    "/_": {
      "filePath": "_.tsx",
      "children": [
        "/_/(auth)/login",
        "/_/(app)/",
        "/_/(app)/recipes/new",
        "/_/(app)/recipes/$author/",
        "/_/(app)/recipes/$author/$rkey/"
      ]
    },
    "/_/(auth)/login": {
      "filePath": "_.(auth)/login.tsx",
      "parent": "/_"
    },
    "/_/(app)/": {
      "filePath": "_.(app)/index.lazy.tsx",
      "parent": "/_"
    },
    "/_/(app)/recipes/new": {
      "filePath": "_.(app)/recipes/new.tsx",
      "parent": "/_"
    },
    "/_/(app)/recipes/$author/": {
      "filePath": "_.(app)/recipes/$author/index.lazy.tsx",
      "parent": "/_"
    },
    "/_/(app)/recipes/$author/$rkey/": {
      "filePath": "_.(app)/recipes/$author/$rkey/index.lazy.tsx",
      "parent": "/_"
    }
  }
}
ROUTE_MANIFEST_END */
